/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavBar: typeof import('./components/AppNavBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LandingHero: typeof import('./components/LandingHero.vue')['default']
    LargeScreenMenu: typeof import('./components/Navbar/LargeScreenMenu.vue')['default']
    LargeScrenMenu: typeof import('./components/Navbar/LargeScreenMenu.vue')['default']
    MobileMenu: typeof import('./components/Navbar/MobileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
