name: CI TypeScript Type Check

on: [pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '^20.9.0'
      - run: yarn install
      - run: yarn type-check
